version: '3'

services:
    web-node-js:
        image: atisak/nodejs:latest
        ports:
            - "3001:3001"
        environment:
            - MONGODB_ADDON_URI=mongodb://mongodb:27018/test
    mongodb:
        image: mongo:latest
        ports: 
            - "27018:27018"
        
