version: '3'

services:
    web-node-js:
        image: blkwarrior/nodejs:latest
        ports:
            - "3333:3000"
        environment:
            - MONGODB_ADDON_URI=mongodb://mongodb:27017/test
    mongodb:
        image: mongo:3.1
        ports: 
            - "27017:27017"
        
